spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/wisebot_user_database
    username: postgres
    password: password

  jpa:
    show-sql: true

logging:
  level:
    root: INFO