spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:wisebot_user_database}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}

  jpa:
    show-sql: false

app:
  upload:
    avatar-dir: ${AVATAR_UPLOAD_DIR:wisebot-data/avatars}

logging:
  level:
    root: INFO
