server:
  port: 8085
  compression:
    enabled: true
    mime-types: application/json

spring:
  application:
    name: billing-service
  profiles:
    active: @spring.profiles.active@

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

vnpay:
  tmn-code: ${VNPAY_TMN_CODE:ULOKUI1Z}
  hash-secret: ${VNPAY_HASH_SECRET:CF4HDXVL71PEXISXW2Z5HPW1BI9RT1O5}
  pay-url: ${VNPAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  return-url: ${VNPAY_RETURN_URL:http://localhost:5173/billing?vnpay_return=true}

