server:
  port: 8084
  compression:
    enabled: true
    mime-types: application/json

spring:
  application:
    name: billing-service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
