spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 0

storage:
  enabled: false
  base-path: ${STORAGE_BASE_PATH:./build/test-uploads}

logging:
  level:
    root: INFO
