spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: ${SERVER_PORT:8081}

storage:
  enabled: true
  base-path: ${STORAGE_BASE_PATH:/var/lib/wisebot/documents}

logging:
  level:
    root: INFO
