import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'vi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.knowledge': 'Knowledge Base',
    'nav.playground': 'Chatbot Playground',
    'nav.integration': 'Integration & Embed',
    'nav.team': 'Team Management',
    'nav.analytics': 'Usage Statistics',
    'nav.users': 'User Management',
    'nav.billing': 'Billing & Payments',
    'nav.settings': 'Settings',
    'nav.api_keys': 'API Keys',
    'header.system_admin': 'System Admin',
    'header.workspace_owner': 'Workspace Owner',
    'header.workspace_user': 'Workspace User',
    'dashboard.welcome': 'Welcome back, Alex!',
    'dashboard.subtitle': "Here's what's happening with your AI agents today.",
    'dashboard.stats.conversations': 'Total Conversations',
    'dashboard.stats.active_users': 'Message Quota',
    'dashboard.stats.avg_time': 'Avg Response Time',
    'dashboard.stats.resolution': 'Resolution Rate',
    'dashboard.chart.title': 'Conversations Over Time',
    'dashboard.chart.desc': 'Daily trend of incoming message volumes',
    'dashboard.table.title': 'Top Questions',
    'dashboard.table.desc': 'Common topics your users are asking about.',
    'dashboard.table.category': 'Question Category',
    'dashboard.table.volume': 'Volume',
    'dashboard.table.change': 'Change',
    'dashboard.table.action': 'Action',
    'dashboard.view_all': 'View All',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.quick_actions.knowledge_desc': 'Manage and upload your data sources.',
    'dashboard.quick_actions.playground_desc': 'Test and refine your AI models directly.',
    'dashboard.quick_actions.api_keys_desc': 'Configure access for your applications.',
    'dashboard.action.create_bot': 'Create New Bot',
    'dashboard.action.upload_data': 'Upload Knowledge',
    'dashboard.action.invite_team': 'Invite Team',
    'dashboard.activity.title': 'Recent Activity',
    'dashboard.status.operational': 'All systems operational',
    'dashboard.status.syncing': 'Syncing data...',
    'dashboard.stats.total_users': 'Total Platform Users',
    'dashboard.stats.mrr': 'Monthly Recurring Revenue',
    'dashboard.stats.system_health': 'System Health',
    'dashboard.stats.error_rate': 'Error Rate',
    'dashboard.conversation_volume': 'Conversation Volume',
    'dashboard.channel.web': 'Web Chat',
    'dashboard.channel.mobile': 'Mobile App',
    'dashboard.channel.api': 'API',
    'dashboard.plan_distribution': 'Plan Distribution',
    'dashboard.plan.free': 'Free',
    'dashboard.plan.pro': 'Pro',
    'dashboard.plan.enterprise': 'Enterprise',
    'dashboard.admin_welcome': 'System Overview',
    'dashboard.admin_subtitle': 'Real-time performance of the entire platform.',
    'dashboard.admin.chart_title': 'System Traffic',
    'dashboard.admin.stable': 'Stable',
    'dashboard.admin.activity.upgrade': 'Workspace "TechCorp" upgraded to Enterprise Plan',
    'dashboard.admin.activity.signup': 'New platform registration: "Global Logistics Ltd"',
    'dashboard.admin.activity.system': 'System maintenance scheduled for Sunday 02:00 UTC',
    'dashboard.admin.activity.error': 'High error rate detected in API Gateway (Region: US-East)',
    'dashboard.activity.sync': 'Knowledge base "Product FAQ" synced successfully',
    'dashboard.activity.user': 'New team member "Sarah Chen" joined the workspace',
    'dashboard.activity.security': 'New API Key generated for production environment',
    'dashboard.activity.alert': 'Monthly message quota reached 80%',
    'dashboard.activity.bot': 'Bot "Support Assistant" updated to v2.4.1',
    'dashboard.activity.team': 'Sarah Chen changed workspace permissions for "Dev Team"',
    'dashboard.activity.knowledge': 'Knowledge base "API Documentation" auto-sync scheduled',
    'dashboard.activity.alert2': 'Daily message limit reset for Starter plan',
    'dashboard.admin.activity.security': 'Failed login attempt from IP 192.168.1.105 (User: admin)',
    'dashboard.admin.activity.billing': 'Invoice #INV-2026-004 paid by "Creative Studio"',
    'dashboard.admin.activity.system2': 'Database backup completed successfully',
    'dashboard.admin.activity.user': 'User "Mark Wilson" deactivated their account',
    'activity_log.search_placeholder': 'Search activities...',
    'activity_log.no_activities': 'No activities found',
    'activity_log.no_activities_desc': 'Try adjusting your search or filters.',
    'activity_log.view_details': 'View Details',
    'time.mins_ago': '{mins} mins ago',
    'time.hour_ago': '1 hour ago',
    'time.hours_ago': '{hours} hours ago',
    'time.day_ago': '1 day ago',
    'dashboard.action.manage_users': 'Manage Users',
    'dashboard.action.system_settings': 'System Settings',
    'dashboard.action.view_logs': 'View System Logs',
    'dashboard.activity.desc': 'Full history of system events',
    'common.close': 'Close',
    'auth.welcome': 'Welcome Back',
    'auth.welcome_desc': 'Enter your credentials to access your workspace.',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.forgot_password': 'Forgot password?',
    'auth.remember_me': 'Remember me for 30 days',
    'auth.sign_in': 'Sign In',
    'auth.or_continue': 'Or continue with',
    'auth.no_account': "Don't have an account?",
    'auth.create_account': 'Create an account',
    'auth.register.title': 'Create Account',
    'auth.register.desc': 'Join 10,000+ teams building the future of AI.',
    'auth.register.full_name': 'Full Name',
    'auth.register.submit': 'Register',
    'auth.register.have_account': 'Already have an account?',
    'auth.register.login': 'Sign In',
    'validation.required': 'This field is required.',
    'validation.email': 'Must be a valid Gmail address (e.g. example@gmail.com).',
    'validation.password_min': 'Password must be at least {min} characters.',
    'validation.password_match': 'Passwords do not match.',
    'validation.name_min': 'Name must be at least {min} characters.',
    'validation.terms': 'Please agree to the terms.',
    'validation.login_failed': 'Invalid login response.',
    'landing.hero.title_1': 'Build Your AI Chatbot ',
    'landing.hero.title_2': 'in Minutes',
    'landing.hero.subtitle': 'Train your AI on your own documents and provide 24/7 customer support without lifting a finger.',
    'landing.hero.start': 'Start Free',
    'landing.hero.demo': 'Book Demo',
    'landing.hero.social_proof': 'Join 500+ businesses automating support',
    'landing.hero.mockup.preview': 'Live Preview',
    'landing.hero.mockup.bot_1': "Hello! I'm your AI assistant. How can I help you today?",
    'landing.hero.mockup.user': 'How do I integrate this into my Shopify store?',
    'landing.hero.mockup.bot_2': 'Integrating with Shopify is easy! Just install our app from the Shopify App Store or paste a single line of code into your theme. liquid file.',
    'landing.hero.mockup.input': 'Type your message...',
    'landing.hero.badge': 'New: GPT-4o Integration',
    'landing.features.title': 'Powerful Features for Your Business',
    'landing.features.subtitle': 'Everything you need to automate your customer support with world-class artificial intelligence.',
    'landing.features.f1.title': 'AI trained on your data',
    'landing.features.f1.desc': 'Upload PDFs, docs, or websites to train your bot instantly with zero coding.',
    'landing.features.f2.title': 'Easy integration',
    'landing.features.f2.desc': 'Embed your chatbot on any website with a single line of code in seconds.',
    'landing.features.f3.title': 'Analytics dashboard',
    'landing.features.f3.desc': 'Track performance, user satisfaction, and deep conversation history insights.',
    'landing.features.f4.title': 'Multi-language',
    'landing.features.f4.desc': 'Support customers in over 100 languages automatically and flawlessly.',
    'landing.pricing.title': 'Simple, transparent pricing',
    'landing.pricing.subtitle': "Choose the plan that's right for your business.",
    'landing.get_started': 'Get Started',
    'landing.nav.features': 'Features',
    'landing.nav.how_it_works': 'How it Works',
    'landing.how.title': 'How it Works',
    'landing.how.subtitle': 'Get your AI chatbot up and running in three simple steps.',
    'landing.how.step1.title': '1. Connect Data',
    'landing.how.step1.desc': 'Upload your documents or link your website. We securely process and index your content.',
    'landing.how.step2.title': '2. Customize Bot',
    'landing.how.step2.desc': 'Set the tone, personality, and appearance of your bot to match your brand identity.',
    'landing.how.step3.title': '3. Embed & Engage',
    'landing.how.step3.desc': 'Copy a single line of code to add the widget to your site and start helping customers.',
    'landing.nav.pricing': 'Pricing',
    'landing.nav.docs': 'Documentation',
    'landing.docs.title': 'Developer Documentation',
    'landing.docs.subtitle': 'Everything you need to integrate WiseBot into your application.',
    'landing.docs.quickstart': 'Quickstart Guide',
    'landing.docs.quickstart.desc': 'Get up and running in less than 5 minutes.',
    'landing.docs.api': 'API Reference',
    'landing.docs.api.desc': 'Detailed documentation for our REST API endpoints.',
    'landing.docs.sdks': 'Client SDKs',
    'landing.docs.sdks.desc': 'Libraries for React, Vue, Python, and Node.js.',
    'landing.docs.webhooks': 'Webhooks',
    'landing.docs.webhooks.desc': 'Listen to real-time events from your chatbots.',
    'landing.docs.view_all': 'View Full Documentation',
    'landing.features.kb.title': 'Knowledge Base',
    'landing.features.kb.desc': 'Upload PDFs, DOCX, or URLs to train your bot on your specific data.',
    'landing.features.widget.title': 'Custom Widget',
    'landing.features.widget.desc': 'Fully brandable chat widget that matches your website design perfectly.',
    'landing.features.analytics.title': 'Advanced Analytics',
    'landing.features.analytics.desc': 'Track every conversation and gain insights into user behavior.',
    'landing.features.api.title': 'Secure API',
    'landing.features.api.desc': 'Enterprise-grade security with encrypted API keys and access control.',
    'landing.features.cdn.title': 'Global CDN',
    'landing.features.cdn.desc': 'Lightning fast responses served from edge locations worldwide.',
    'landing.features.team.title': 'Team Collaboration',
    'landing.features.team.desc': 'Invite your team and manage roles with granular permissions.',
    'landing.pricing.popular': 'Most Popular',
    'landing.pricing.contact': 'Contact Sales',
    'landing.pricing.free.name': 'Free',
    'landing.pricing.plus.name': 'Plus',
    'landing.pricing.pro.name': 'Pro',
    'landing.footer.tagline': 'Empowering businesses with intelligent AI solutions that drive growth and customer satisfaction.',
    'landing.footer.product': 'Product',
    'landing.footer.company': 'Company',
    'landing.footer.legal': 'Legal',
    'landing.footer.rights': '© 2024 WiseBot Inc. All rights reserved.',
    'landing.footer.made_with': 'Made with',
    'landing.footer.by_team': 'by the WiseBot Team',
    'landing.footer.links.features': 'Features',
    'landing.footer.links.pricing': 'Pricing',
    'landing.footer.links.docs': 'Documentation',
    'landing.footer.links.api': 'API Reference',
    'landing.footer.links.about': 'About Us',
    'landing.footer.links.careers': 'Careers',
    'landing.footer.links.blog': 'Blog',
    'landing.footer.links.contact': 'Contact',
    'landing.footer.links.privacy': 'Privacy Policy',
    'landing.footer.links.terms': 'Terms of Service',
    'landing.footer.links.cookie': 'Cookie Policy',
    'landing.footer.links.security': 'Security',
    'landing.pricing.free.f1': '1 Chatbot',
    'landing.pricing.free.f2': '1,000 Messages/mo',
    'landing.pricing.free.f3': 'Standard Support',
    'landing.pricing.plus.f1': '5 Chatbots',
    'landing.pricing.plus.f2': '10,000 Messages/mo',
    'landing.pricing.plus.f3': 'Advanced Analytics',
    'landing.pricing.plus.f4': 'Priority Support',
    'landing.pricing.pro.f1': 'Unlimited Chatbots',
    'landing.pricing.pro.f2': 'Unlimited Messages',
    'landing.pricing.pro.f3': 'Custom Branding',
    'landing.pricing.pro.f4': 'API Access',
    'landing.pricing.pro.f5': '24/7 Dedicated Support',
    'auth.reset.title': 'Reset Password',
    'auth.reset.desc': "Enter your email and we'll send you a link to reset your password.",
    'auth.reset.submit': 'Send Reset Link',
    'auth.reset.back': 'Back to Login',
    'auth.verify.title': 'Verify Your Email',
    'auth.verify.desc': "We've sent a verification link to",
    'auth.verify.instruction': "Please check your inbox and click the link to activate your account. If you don't see it, check your spam folder.",
    'auth.verify.resend': 'Resend Verification Email',
    'auth.verify.dashboard': 'Go to Dashboard',
    'widget.title': 'Widget Customization',
    'widget.subtitle': 'Personalize how the chatbot looks on your site.',
    'widget.settings_tab': 'Settings',
    'widget.preview_tab': 'Preview',
    'widget.identity': 'Bot Identity',
    'widget.display_name': 'Display Name',
    'widget.welcome_message': 'Welcome Message',
    'widget.bot_icon': 'Bot Icon',
    'widget.icon_color': 'Icon Color',
    'widget.branding': 'Branding & Style',
    'widget.primary_color': 'Primary Color',
    'widget.position': 'Widget Position',
    'widget.pos_left': 'Bottom Left',
    'widget.pos_right': 'Bottom Right',
    'widget.layout': 'Layout Options',
    'widget.show_citations': 'Show Source Citations',
    'widget.enable_uploads': 'Enable File Uploads',
    'widget.publish': 'Publish Changes',
    'widget.publishing': 'Publishing...',
    'widget.published': 'Published',
    'widget.publish_success': 'Widget settings published successfully!',
    'widget.embed_title': 'Embed on your site',
    'widget.embed_desc': 'Copy and paste this code into your website\'s <head> tag.',
    'widget.copy_code': 'Copy Code',
    'widget.view_demo': 'View Live Demo',
    'widget.view_demo_desc': 'Want to see how it looks on a real page before deploying?',
    'demo.mode': 'Demo Mode',
    'demo.title': 'Live Preview: Your Website',
    'demo.nav.product': 'Product',
    'demo.nav.solutions': 'Solutions',
    'demo.nav.pricing': 'Pricing',
    'demo.hero.badge': 'Trusted by 500+ companies',
    'demo.hero.title_1': 'Automate your',
    'demo.hero.title_2': 'Customer Support',
    'demo.hero.desc': 'This is a live demo of how your customized WiseBot widget will look and behave on your actual website. Experience the seamless integration first-hand.',
    'demo.hero.cta_primary': 'Start Free Trial',
    'demo.hero.cta_secondary': 'Book a Demo',
    'demo.feature.1.title': 'Instant Answers',
    'demo.feature.1.desc': 'Reduce support tickets by 70% with AI-powered instant resolutions that understand context.',
    'demo.feature.2.title': 'Secure Data',
    'demo.feature.2.desc': 'Your data is encrypted and stored securely in our private cloud with SOC2 compliance.',
    'demo.feature.3.title': 'Multi-language',
    'demo.feature.3.desc': 'Support your customers in over 50 languages automatically with perfect translation.',
    'demo.testimonial.1.text': '"WiseBot has completely transformed how we interact with our customers. The setup was instant and the AI is incredibly smart."',
    'demo.testimonial.1.author': 'Sarah Jenkins',
    'demo.testimonial.1.role': 'CEO at TechFlow Global',
    'demo.testimonial.2.text': '"The integration was seamless. Our support team is now focusing on complex issues while WiseBot handles the routine queries perfectly."',
    'demo.testimonial.2.author': 'Mark Thompson',
    'demo.testimonial.2.role': 'CTO at InnovateX',
    'demo.testimonial.3.text': '"WiseBot\'s ability to learn from our knowledge base is impressive. It provides accurate answers in seconds, improving our customer satisfaction significantly."',
    'demo.testimonial.3.author': 'Elena Rodriguez',
    'demo.testimonial.3.role': 'Customer Success Manager at CloudScale',
    'demo.cta.title': 'Ready to boost your productivity?',
    'demo.cta.desc': 'Join thousands of companies already using WiseBot to power their customer success teams.',
    'demo.cta.button': 'Get Started for Free',
    'demo.footer.privacy': 'Privacy',
    'demo.footer.terms': 'Terms',
    'demo.footer.contact': 'Contact',
    'demo.footer.copy': '© 2026 Your Company. Powered by WiseBot AI.',
    'widget.code_copied': 'Code copied to clipboard!',
    'widget.preview.online': 'Online',
    'widget.preview.ask': 'Ask a question...',
    'api.title': 'API Keys',
    'api.quickstart': 'API Quickstart',
    'api.subtitle': 'Manage secure access to your AI models and resources.',
    'api.generate': 'Generate New Key',
    'api.table.name': 'Name',
    'api.table.key': 'Key',
    'api.table.date': 'Created Date',
    'api.table.used': 'Last Used',
    'api.table.actions': 'Actions',
    'api.security.title': 'API Security Best Practices',
    'api.security.desc': 'Never share your API keys in public repositories or client-side code. Use environment variables to store your keys securely and rotate them regularly to minimize risk.',
    'api.security.guide': 'View Security Guide',
    'api.docs.title': 'API Documentation',
    'api.docs.desc': 'Learn how to integrate our AI models into your application using our comprehensive documentation, client libraries, and SDKs.',
    'api.docs.read': 'Read Documentation',
    'api.modal.title': 'Generate New API Key',
    'api.modal.name': 'Key Name',
    'api.modal.placeholder': 'e.g. Production Master',
    'api.modal.cancel': 'Cancel',
    'api.modal.success': 'API Key generated successfully!',
    'api.modal.copy_msg': 'Make sure to copy your API key now. You won\'t be able to see it again.',
    'api.confirm.revoke.title': 'Revoke API Key',
    'api.confirm.revoke.msg': 'Are you sure you want to revoke',
    'api.confirm.revoke.undone': 'This action cannot be undone and any application using this key will stop working.',
    'api.copy.success': 'API Key copied to clipboard!',
    'api.guide.title': 'API Security Guide',
    'api.guide.step1.title': 'Keep your keys secret',
    'api.guide.step1.desc': 'Your API keys provide full access to your account. Never commit them to version control (GitHub, GitLab) or include them in client-side code.',
    'api.guide.step2.title': 'Use Environment Variables',
    'api.guide.step2.desc': 'Store keys in .env files or secure vault services. Access them on the server-side only.',
    'api.guide.step3.title': 'Rotate Keys Regularly',
    'api.guide.step3.desc': 'Change your keys every 90 days to minimize the impact of a potential leak.',
    'api.guide.step4.title': 'Restrict Access',
    'api.guide.step4.desc': 'Create separate keys for different environments (Dev, Staging, Prod) to isolate risks.',
    'api.docs.modal.title': 'API Reference',
    'api.docs.endpoint.title': 'Base Endpoint',
    'api.docs.auth.title': 'Authentication',
    'api.docs.auth.desc': 'All API requests must include your API key in the Authorization header.',
    'api.docs.example.title': 'Request Example',
    'billing.title': 'Billing & Subscriptions',
    'billing.subtitle': 'Manage pricing plans, track revenue, and monitor user subscriptions.',
    'billing.create_plan': 'Create New Plan',
    'billing.payment_methods.title': 'Payment Methods',
    'billing.payment_methods.desc': 'Manage your credit cards and payment preferences.',
    'billing.payment_methods.add': 'Add Payment Method',
    'billing.payment_methods.add_success': 'Payment method added successfully',
    'billing.payment_methods.save': 'Save Payment Method',
    'billing.payment_methods.delete_confirm': 'Delete Payment Method',
    'billing.payment_methods.delete_desc': 'Are you sure you want to delete this payment method?',
    'billing.payment_methods.delete_confirm_btn': 'Delete',
    'billing.payment_methods.delete_success': 'Payment method deleted successfully',
    'billing.payment_methods.primary': 'Primary',
    'billing.payment_methods.expires': 'Expires',
    'billing.payment_methods.remove': 'Remove',
    'billing.details.title': 'Billing Details',
    'billing.details.desc': 'Update your billing address and tax information.',
    'billing.details.address': 'Billing Address',
    'billing.details.city': 'City',
    'billing.details.country': 'Country',
    'billing.details.tax_id': 'Tax ID / VAT',
    'billing.plans.free': 'Free',
    'billing.plans.plus': 'Plus',
    'billing.plans.pro': 'Pro',
    'billing.plans.free.f1': 'Up to 1,000 messages',
    'billing.plans.free.f2': '1 Knowledge Base',
    'billing.plans.free.f3': 'Standard Support',
    'billing.plans.plus.f1': 'Up to 10,000 messages',
    'billing.plans.plus.f2': '5 Knowledge Bases',
    'billing.plans.plus.f3': 'Priority Support',
    'billing.plans.plus.f4': 'API Access',
    'billing.plans.pro.f1': 'Unlimited messages',
    'billing.plans.pro.f2': 'Unlimited Knowledge Bases',
    'billing.plans.pro.f3': 'Dedicated Support',
    'billing.plans.pro.f4': 'Custom Integration',
    'billing.plans.pro.f5': 'Advanced Analytics',
    'billing.plans.select': 'Select Plan',
    'billing.plans.current': 'Current Plan',
    'billing.plans.popular': 'Most Popular',
    'billing.plans.features': 'Key Features',
    'billing.plans.monthly': 'Monthly',
    'billing.plans.yearly': 'Yearly',
    'billing.plans.save_20': 'Save 20%',
    'billing.plans.billed': 'Billed',
    'billing.alerts.title': 'Usage Alerts',
    'billing.alerts.desc': 'Get notified when you reach certain usage thresholds.',
    'billing.alerts.threshold': 'Notification Threshold',
    'billing.alerts.email': 'Send email alert',
    'billing.alerts.push': 'Send push notification',
    'billing.mrr': 'Monthly Recurring Revenue',
    'billing.active_subs': 'Active Subscriptions',
    'billing.failed_payments': 'Failed Payments',
    'billing.recent_subs': 'Recent Subscriptions',
    'billing.view_all': 'View All',
    'billing.table.user': 'User',
    'billing.table.plan': 'Plan',
    'billing.table.amount': 'Amount',
    'billing.table.status': 'Status',
    'billing.table.next_billing': 'Next Billing',
    'billing.table.action': 'Action',
    'billing.manage': 'Manage',
    'billing.user.subtitle': 'Manage your plan, payment methods, and view invoices.',
    'billing.payment_methods': 'Payment Methods',
    'billing.no_payment_methods': 'No payment methods',
    'billing.no_payment_methods_desc': 'Please add a payment method to continue with the upgrade.',
    'billing.upgrade': 'Upgrade Plan',
    'billing.upgrade_desc': 'Choose the plan that fits your growth.',
    'billing.upgrade_success': 'Successfully upgraded to {plan} plan!',
    'billing.downgrade_success': 'Successfully switched to Free plan.',
    'billing.current_plan': 'Current Plan',
    'billing.current_plan.desc': 'You are currently on the',
    'billing.current_plan.next_billing': 'Next billing date',
    'billing.current_plan.need_more': 'Need more resources?',
    'billing.payment_methods.manage': 'Manage your saved payment methods.',
    'billing.payment_methods.add_new': 'Add New Card',
    'billing.payment_methods.cardholder_name': 'Cardholder Name',
    'billing.payment_methods.card_number': 'Card Number',
    'billing.payment_methods.expiry': 'Expiry Date',
    'billing.payment_methods.cvc': 'CVC',
    'billing.payment_methods.billing_address': 'Billing Address',
    'billing.active': 'Active',
    'billing.free_forever': 'Free forever',
    'billing.pay_now': 'Pay Now',
    'billing.billed_monthly': 'Billed monthly',
    'billing.next_renewal': 'Next renewal on',
    'billing.cancel': 'Cancel Subscription',
    'billing.usage.messages': 'Message Quota',
    'billing.usage.storage': 'Knowledge Base Storage',
    'billing.usage.reset': 'Resets in',
    'billing.usage.capacity': 'of total capacity used',
    'billing.secure_ssl': 'Secure SSL Encryption',
    'billing.cancel_anytime': 'Cancel Anytime',
    'billing.history': 'Payment History',
    'billing.history_desc': 'View and download all your past invoices.',
    'billing.table.invoice': 'Invoice ID',
    'billing.table.date': 'Date',
    'billing.order_summary': 'Order Summary',
    'billing.total_due': 'Total due',
    'billing.payment_method': 'Payment method',
    'billing.secure_note': 'Your payment info is encrypted and secure. You can cancel anytime.',
    'billing.no_plans': 'No plans available',
    'billing.loading': 'Loading...',
    'billing.subscribing': 'Setting up your subscription...',
    'billing.no_data': 'No data available',
    'billing.plans.selected': 'Selected',
    'common.back': 'Back',
    'notifications.title': 'Notifications',
    'notifications.view_all': 'View all',
    'notifications.mark_read': 'Mark all as read',
    'notifications.empty': 'No new notifications',
    'notifications.new_message': 'New message from',
    'notifications.system_update': 'System Update',
    'notifications.billing_alert': 'Billing Alert',
    'playground.title': 'Conversation',
    'playground.clear': 'Clear Chat',
    'playground.placeholder': 'Type your message...',
    'playground.sources': 'Source Citations',
    'playground.settings': 'Model Settings',
    'playground.temp': 'Temperature',
    'playground.temp_desc': 'Controls randomness: Lower is more focused and deterministic.',
    'playground.topk': 'Top-K',
    'playground.topk_desc': 'Limits vocabulary to top K most likely tokens.',
    'playground.save': 'Save Configuration',
    'playground.save_success': 'Configuration saved successfully!',
    'playground.role.assistant': 'AI Assistant',
    'playground.role.user': 'You',
    'kb.title': 'Knowledge Base',
    'kb.subtitle': 'Manage the data sources that power your chatbot responses.',
    'kb.create': 'Create Knowledge Base',
    'kb.manage.title': 'Manage Knowledge Bases',
    'kb.manage.subtitle': 'Edit, delete, or sync your existing data sources.',
    'kb.no_sources': 'No knowledge bases found.',
    'kb.sources.title': 'Managed Data Sources',
    'kb.upload.title': 'Upload Documents',
    'kb.upload.target': 'Target Knowledge Base',
    'kb.upload.drop': 'Drop files here or click to upload',
    'kb.upload.limit': 'Supports PDF, DOCX, TXT (Max 10MB)',
    'kb.recent.title': 'Recent Uploads',
    'kb.table.file': 'File Name',
    'kb.table.type': 'Type',
    'kb.table.status': 'Status',
    'kb.table.size': 'Size',
    'kb.table.date': 'Date',
    'kb.table.showing': 'Showing',
    'kb.table.of': 'of',
    'kb.table.docs': 'documents',
    'kb.modal.create': 'Create Knowledge Base',
    'kb.modal.edit': 'Edit Knowledge Base',
    'kb.modal.name': 'Name',
    'kb.modal.name_placeholder': 'e.g., Customer Support FAQ',
    'kb.modal.desc': 'Description',
    'kb.modal.desc_placeholder': 'Briefly describe what this knowledge base contains...',
    'kb.modal.type': 'Source Type',
    'kb.modal.type.doc': 'Document Upload',
    'kb.modal.type.doc_desc': 'Upload PDF, DOCX, TXT files directly.',
    'kb.modal.type.web': 'Website Crawl',
    'kb.modal.type.web_desc': 'Extract content from a public website.',
    'kb.modal.type.notion': 'Notion Integration',
    'kb.modal.type.notion_desc': 'Sync pages from your Notion workspace.',
    'kb.confirm.delete.title': 'Delete Knowledge Base',
    'kb.confirm.delete.msg': 'Are you sure you want to delete',
    'kb.confirm.delete.undone': 'This action cannot be undone.',
    'kb.confirm.edit.title': 'Confirm Changes',
    'kb.confirm.edit.msg': 'Are you sure you want to save these changes to',
    'kb.preview': 'Preview Document',
    'kb.preview_desc': 'Viewing a snapshot of the document content.',
    'kb.preview_not_available': 'Preview is not available for this file type.',
    'users.title': 'User Management',
    'users.subtitle': 'Manage all system users, their global roles, and account status.',
    'users.create': 'Create User',
    'users.edit': 'Edit User',
    'users.stats.total': 'Total Users',
    'users.stats.admins': 'Admins',
    'users.stats.active': 'Active Now',
    'users.stats.suspended': 'Suspended',
    'users.table.user': 'User',
    'users.table.role': 'Global Role',
    'users.table.workspaces': 'Workspaces',
    'users.table.status': 'Status',
    'users.table.last_login': 'Last Login',
    'users.table.actions': 'Actions',
    'users.no_users': 'No users found.',
    'users.showing': 'Showing',
    'users.users': 'users',
    'users.details.title': 'User Details',
    'users.confirm.delete.title': 'Delete User',
    'users.confirm.delete.msg': 'Are you sure you want to delete user',
    'users.confirm.delete.undone': 'This action cannot be undone.',
    'team.title': 'Team Management',
    'team.subtitle': 'Invite and manage your team members and their permissions.',
    'team.invite': 'Invite Member',
    'team.invite_new': 'Invite New Member',
    'team.invite_sent': 'Invite Sent',
    'team.edit_member': 'Edit Member',
    'team.remove_member': 'Remove Member',
    'team.no_members': 'No team members found.',
    'team.stats.total': 'Total Members',
    'team.stats.admins': 'Admins/Owners',
    'team.stats.pending': 'Pending Invites',
    'team.stats.seats': 'Seats Used',
    'team.table.name': 'Name',
    'team.table.email': 'Email',
    'team.table.role': 'Role',
    'team.table.status': 'Status',
    'team.table.actions': 'Actions',
    'team.showing': 'Showing',
    'team.members': 'members',
    'team.full_name': 'Full Name',
    'team.email_address': 'Email Address',
    'team.link_generated': 'Invite Link Generated',
    'team.link_sent_to': 'An invitation link has been generated for',
    'team.copy_manually': 'Copy link manually',
    'team.copied': 'Copied to clipboard!',
    'team.copy': 'Copy',
    'team.invite_desc': 'Enter the email of the person you want to invite. They will receive a link to register and join your team.',
    'team.generate_link': 'Generate Invite Link',
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Track performance, user engagement, and conversation trends.',
    'analytics.export': 'Export Data',
    'analytics.chart.volume': 'Conversation Volume',
    'analytics.chart.activity': 'Real-time Activity',
    'analytics.admin.overview': 'Admin Overview',
    'analytics.admin.total_users': 'Total Users',
    'analytics.admin.mrr': 'MRR',
    'analytics.admin.system_health': 'System Health',
    'analytics.admin.api_requests': 'API Requests',
    'analytics.admin.user_growth': 'User Growth',
    'analytics.admin.plan_distribution': 'Plan Distribution',
    'analytics.admin.system_load': 'System Load',
    'analytics.admin.user_analytics': 'User Analytics',
    'analytics.admin.new_users': 'New Users',
    'analytics.admin.active_users': 'Active Users',
    'analytics.admin.stable': 'Stable',
    'analytics.admin.requests': 'Requests',
    'analytics.admin.errors': 'Errors',
    'analytics.admin.server_load': 'Server Load',
    'analytics.table.title': 'Most Asked Queries',
    'analytics.table.query': 'Query',
    'analytics.table.count': 'Count',
    'analytics.table.trend': 'Trend',
    'analytics.view_full': 'View Full Report',
    'analytics.period.7d': 'Last 7 Days',
    'analytics.period.30d': 'Last 30 Days',
    'analytics.period.90d': 'Last 90 Days',
    'dashboard.chart.last_7d': 'Last 7 Days',
    'dashboard.chart.last_30d': 'Last 30 Days',
    'dashboard.chart.trend_up': 'Last 7 Days (+15.3%)',
    'dashboard.category.billing': 'Billing & Subscription',
    'dashboard.category.security': 'Account Security',
    'dashboard.category.api': 'API Documentation',
    'settings.profile': 'Profile Settings',
    'settings.profile.desc': 'Update your personal details and public profile.',
    'settings.profile.title': 'Profile Information',
    'settings.security': 'Security & Privacy',
    'settings.security.desc': 'Manage your password and account security settings.',
    'settings.security.password': 'Change Password',
    'settings.security.password.desc': 'Last changed 3 months ago',
    'settings.security.password.current': 'Current Password',
    'settings.security.password.new': 'New Password',
    'settings.security.password.confirm': 'Confirm New Password',
    'settings.security.password.save': 'Update Password',
    'settings.security.password.cancel': 'Cancel',
    'settings.security.2fa': 'Two-Factor Authentication',
    'settings.security.2fa.desc': 'Enabled • SMS & Authenticator App',
    'settings.security.sessions': 'Active Sessions',
    'settings.security.sessions.desc': 'Manage devices currently logged in',
    'settings.notifications': 'Notification Preferences',
    'settings.notifications.desc': 'Choose what updates you want to receive and how.',
    'settings.notifications.email': 'Email Notifications',
    'settings.notifications.email.desc': 'Receive daily summaries and important alerts via email.',
    'settings.notifications.push': 'Push Notifications',
    'settings.notifications.push.desc': 'Get real-time updates in your browser.',
    'settings.notifications.marketing': 'Marketing & Updates',
    'settings.notifications.marketing.desc': 'Receive news about new features and promotions.',
    'settings.notifications.save': 'Save Preferences',
    'settings.apps': 'Connected Apps',
    'settings.apps.desc': 'Manage third-party integrations and connected services.',
    'settings.apps.github': 'GitHub',
    'settings.apps.github.desc': 'Connected as @alexrivet',
    'settings.apps.slack': 'Slack',
    'settings.apps.slack.desc': 'Not connected',
    'settings.apps.trello': 'Trello',
    'settings.apps.trello.desc': 'Not connected',
    'settings.apps.disconnect': 'Disconnect',
    'settings.apps.connect': 'Connect',
    'settings.workspace': 'Workspace Settings',
    'settings.workspace.desc': 'Manage global workspace configuration and billing.',
    'settings.workspace.name': 'Workspace Name',
    'settings.workspace.members': 'Manage Members',
    'settings.workspace.members.desc': 'Invite users and manage roles.',
    'settings.workspace.billing': 'Billing & Plans',
    'settings.workspace.billing.desc': 'View invoices and upgrade plan.',
    'settings.workspace.danger': 'Danger Zone',
    'settings.workspace.danger.desc': 'Once you delete a workspace, there is no going back. Please be certain.',
    'settings.workspace.delete': 'Delete Workspace',
    'header.internal_workspace': 'Internal Workspace',
    'header.ai_platform': 'WiseBot',
    'settings.title': 'Settings',
    'settings.description': 'Manage your account preferences and workspace configuration.',
    'settings.language': 'Language Settings',
    'settings.language.desc': 'Choose your preferred language for the interface.',
    'settings.language.select': 'Select Language',
    'common.create': 'Create',
    'common.save': 'Save Changes',
    'common.save_short': 'Save',
    'common.cancel': 'Cancel',
    'common.change': 'Change',
    'common.processing': 'Processing...',
    'common.english': 'English',
    'common.vietnamese': 'Vietnamese',
    'common.search': 'Search...',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.done': 'Done',
    'common.select': 'Select File',
    'common.prev': 'Previous',
    'common.next': 'Next',
    'common.confirm': 'Confirm',
    'common.retry': 'Retry Sync',
    'common.view_details': 'View Details',
    'common.cannot_be_undone': 'This action cannot be undone.',
    'billing.support.phone': 'Phone Number',
    'toast.login_success': 'Successfully signed in!',
    'toast.signup_success': 'Account created successfully!',
    'toast.logout_success': 'Successfully signed out.',
    'toast.kb_created': 'Knowledge base created successfully!',
    'toast.kb_updated': 'Knowledge base updated successfully!',
    'toast.kb_deleted': 'Knowledge base deleted successfully.',
    'toast.file_uploaded': 'File uploaded successfully!',
    'toast.api_generated': 'API Key generated successfully!',
    'toast.api_revoked': 'API Key revoked successfully.',
    'toast.user_created': 'User created successfully!',
    'toast.user_updated': 'User updated successfully!',
    'toast.user_deleted': 'User deleted successfully.',
    'toast.error': 'Something went wrong. Please try again.',
    'status.synced': 'Synced',
    'status.live_sync': 'Live Sync',
    'status.idle': 'Idle',
    'status.completed': 'Completed',
    'status.processing': 'Processing',
    'status.failed': 'Failed',
    'settings.profile.timezone': 'Timezone',
    'settings.profile.plan_pro': 'Pro Plan',
    'profile.plan_pro_badge': 'Pro Member',
    'profile.delete_account': 'Delete Account',
    'profile.delete_account_desc': 'Permanently remove your account and all associated data.',
    'profile.view_public': 'View Public Profile',
    'profile.overview': 'Overview',
    'profile.repositories': 'Repositories',
    'profile.projects': 'Projects',
    'profile.packages': 'Packages',
    'profile.stars': 'Stars',
    'profile.followers': 'followers',
    'profile.following': 'following',
    'profile.pinned': 'Pinned',
    'profile.pinned_agents': 'Pinned Agents',
    'profile.activity': 'Activity',
    'profile.conversations_handled': 'conversations handled in the last year',
    'profile.contributions': 'contributions in the last year',
    'billing.payment_methods.set_primary': 'Set Primary',
    'role.admin': 'ADMIN',
    'role.owner': 'OWNER',
    'role.user': 'USER',
    'profile.edit': 'Edit Profile',
    'profile.settings': 'Account Settings',
    'profile.sign_out': 'Sign Out',
    'profile.joined': 'Joined',
    'profile.personal_info': 'Personal Information',
    'profile.personal_info_desc': 'Update your personal details and how others see you.',
    'profile.security': 'Account Security',
    'profile.security.password': 'Change Password',
    'profile.security.password_desc': 'Update your password to keep your account secure.',
    'profile.security.current_password': 'Current Password',
    'profile.security.new_password': 'New Password',
    'profile.security.confirm_password': 'Confirm New Password',
    'profile.security.2fa': 'Two-Factor Authentication (2FA)',
    'profile.security.2fa_desc': 'Add an extra layer of security to your account.',
    'profile.security.2fa_enable': 'Enable 2FA',
    'profile.security.2fa_disable': 'Disable 2FA',
    'profile.security.2fa_status_on': 'Enabled',
    'profile.security.2fa_status_off': 'Disabled',
    'profile.security.update_password': 'Update Password',
    'profile.security.authenticator_app': 'Authenticator App',
    'profile.security.authenticator_desc': 'Use an app like Google Authenticator or Authy.',
    'profile.security.danger_zone': 'Danger Zone',
    'profile.security.delete_account': 'Delete Account',
    'profile.security.delete_account_desc': 'Permanently delete your account and all of your content.',
    'profile.stats.workspaces': 'Workspaces',
    'profile.stats.chatbots': 'Chatbots',
    'profile.stats.messages': 'Messages',
    'profile.stats.team': 'Team Size',
    'profile.bio': 'Bio',
    'profile.location': 'Location',
    'profile.social_links': 'Social Links',
    'profile.website': 'Website',
    'profile.twitter': 'Twitter',
    'profile.github': 'GitHub',
    'profile.linkedin': 'LinkedIn',
    'profile.timezone': 'Timezone',
    'profile.language_region': 'Language & Region',
    'settings.system': 'System Settings',
    'settings.system.desc': 'Manage system-wide preferences like language and appearance.',
    'settings.appearance': 'Appearance',
    'settings.appearance.desc': 'Customize how the interface looks on your device.',
    'settings.theme.light': 'Light Mode',
    'settings.theme.dark': 'Dark Mode',
    'settings.theme.system': 'System Default',
  },
  vi: {
    'nav.dashboard': 'Bảng điều khiển',
    'nav.knowledge': 'Cơ sở tri thức',
    'nav.playground': 'Khu vực thử nghiệm',
    'nav.integration': 'Tích hợp & Nhúng',
    'nav.team': 'Quản lý nhóm',
    'nav.analytics': 'Thống kê sử dụng',
    'nav.users': 'Quản lý người dùng',
    'nav.billing': 'Thanh toán & Gói cước',
    'nav.settings': 'Cài đặt',
    'nav.api_keys': 'Mã API',
    'header.system_admin': 'Quản trị hệ thống',
    'header.workspace_owner': 'Chủ sở hữu',
    'header.workspace_user': 'Người dùng',
    'dashboard.welcome': 'Chào mừng trở lại, Alex!',
    'dashboard.subtitle': 'Đây là những gì đang xảy ra với các trợ lý AI của bạn hôm nay.',
    'dashboard.stats.conversations': 'Tổng số cuộc hội thoại',
    'dashboard.stats.active_users': 'Hạn mức tin nhắn',
    'dashboard.stats.avg_time': 'Thời gian phản hồi TB',
    'dashboard.stats.resolution': 'Tỷ lệ giải quyết',
    'dashboard.chart.title': 'Hội thoại theo thời gian',
    'dashboard.chart.desc': 'Xu hướng hàng ngày của lượng tin nhắn đến',
    'dashboard.table.title': 'Câu hỏi hàng đầu',
    'dashboard.table.desc': 'Các chủ đề phổ biến mà người dùng của bạn đang hỏi.',
    'dashboard.table.category': 'Danh mục câu hỏi',
    'dashboard.table.volume': 'Số lượng',
    'dashboard.table.change': 'Thay đổi',
    'dashboard.table.action': 'Hành động',
    'dashboard.view_all': 'Xem tất cả',
    'dashboard.quick_actions': 'Hành động nhanh',
    'dashboard.quick_actions.knowledge_desc': 'Quản lý và tải lên các nguồn dữ liệu của bạn.',
    'dashboard.quick_actions.playground_desc': 'Kiểm tra và tinh chỉnh trực tiếp các mô hình AI của bạn.',
    'dashboard.quick_actions.api_keys_desc': 'Định cấu hình quyền truy cập cho ứng dụng của bạn.',
    'dashboard.action.create_bot': 'Tạo Bot mới',
    'dashboard.action.upload_data': 'Tải lên dữ liệu',
    'dashboard.action.invite_team': 'Mời thành viên',
    'dashboard.activity.title': 'Hoạt động gần đây',
    'dashboard.status.operational': 'Hệ thống hoạt động bình thường',
    'dashboard.status.syncing': 'Đang đồng bộ dữ liệu...',
    'dashboard.stats.total_users': 'Tổng người dùng nền tảng',
    'dashboard.stats.mrr': 'Doanh thu định kỳ hàng tháng',
    'dashboard.stats.system_health': 'Sức khỏe hệ thống',
    'dashboard.stats.error_rate': 'Tỷ lệ lỗi',
    'dashboard.conversation_volume': 'Lượng hội thoại',
    'dashboard.channel.web': 'Chat trên Web',
    'dashboard.channel.mobile': 'Ứng dụng di động',
    'dashboard.channel.api': 'API',
    'dashboard.plan_distribution': 'Phân bổ gói dịch vụ',
    'dashboard.plan.free': 'Miễn phí',
    'dashboard.plan.pro': 'Chuyên nghiệp',
    'dashboard.plan.enterprise': 'Doanh nghiệp',
    'dashboard.admin_welcome': 'Tổng quan hệ thống',
    'dashboard.admin_subtitle': 'Hiệu suất thời gian thực của toàn bộ nền tảng.',
    'dashboard.admin.chart_title': 'Lưu lượng hệ thống',
    'dashboard.admin.stable': 'Ổn định',
    'dashboard.admin.activity.upgrade': 'Không gian làm việc "TechCorp" đã nâng cấp lên Gói Doanh nghiệp',
    'dashboard.admin.activity.signup': 'Đăng ký nền tảng mới: "Global Logistics Ltd"',
    'dashboard.admin.activity.system': 'Bảo trì hệ thống dự kiến vào Chủ Nhật 02:00 UTC',
    'dashboard.admin.activity.error': 'Phát hiện tỷ lệ lỗi cao trong API Gateway (Khu vực: US-East)',
    'dashboard.activity.sync': 'Cơ sở kiến thức "Product FAQ" đã đồng bộ thành công',
    'dashboard.activity.user': 'Thành viên mới "Sarah Chen" đã tham gia không gian làm việc',
    'dashboard.activity.security': 'Khóa API mới được tạo cho môi trường production',
    'dashboard.activity.alert': 'Hạn mức tin nhắn hàng tháng đã đạt 80%',
    'dashboard.activity.bot': 'Bot "Support Assistant" đã cập nhật lên v2.4.1',
    'dashboard.activity.team': 'Sarah Chen đã thay đổi quyền không gian làm việc cho "Dev Team"',
    'dashboard.activity.knowledge': 'Cơ sở kiến thức "API Documentation" đã lên lịch đồng bộ tự động',
    'dashboard.activity.alert2': 'Giới hạn tin nhắn hàng ngày đã được đặt lại cho gói Starter',
    'dashboard.admin.activity.security': 'Đăng nhập thất bại từ IP 192.168.1.105 (Người dùng: admin)',
    'dashboard.admin.activity.billing': 'Hóa đơn #INV-2026-004 đã được thanh toán bởi "Creative Studio"',
    'dashboard.admin.activity.system2': 'Sao lưu cơ sở dữ liệu hoàn tất thành công',
    'dashboard.admin.activity.user': 'Người dùng "Mark Wilson" đã vô hiệu hóa tài khoản của họ',
    'activity_log.search_placeholder': 'Tìm kiếm hoạt động...',
    'activity_log.no_activities': 'Không tìm thấy hoạt động nào',
    'activity_log.no_activities_desc': 'Thử điều chỉnh tìm kiếm hoặc bộ lọc của bạn.',
    'activity_log.view_details': 'Xem chi tiết',
    'time.mins_ago': '{mins} phút trước',
    'time.hour_ago': '1 giờ trước',
    'time.hours_ago': '{hours} giờ trước',
    'time.day_ago': '1 ngày trước',
    'dashboard.action.manage_users': 'Quản lý người dùng',
    'dashboard.action.system_settings': 'Cài đặt hệ thống',
    'dashboard.action.view_logs': 'Xem nhật ký hệ thống',
    'dashboard.activity.desc': 'Lịch sử đầy đủ các sự kiện hệ thống',
    'common.close': 'Đóng',
    'auth.welcome': 'Chào mừng trở lại',
    'auth.welcome_desc': 'Nhập thông tin đăng nhập để truy cập không gian làm việc.',
    'auth.email': 'Địa chỉ Email',
    'auth.password': 'Mật khẩu',
    'auth.forgot_password': 'Quên mật khẩu?',
    'auth.remember_me': 'Ghi nhớ đăng nhập trong 30 ngày',
    'auth.sign_in': 'Đăng nhập',
    'auth.or_continue': 'Hoặc tiếp tục với',
    'auth.no_account': 'Chưa có tài khoản?',
    'auth.create_account': 'Tạo tài khoản mới',
    'auth.register.title': 'Tạo tài khoản',
    'auth.register.desc': 'Tham gia cùng hơn 10.000 nhóm đang xây dựng tương lai AI.',
    'auth.register.full_name': 'Họ và tên',
    'auth.register.submit': 'Đăng ký',
    'auth.register.have_account': 'Đã có tài khoản?',
    'auth.register.login': 'Đăng nhập',
    'validation.required': 'Vui lòng nhập thông tin.',
    'validation.email': 'Email phải là Gmail (vd: example@gmail.com).',
    'validation.password_min': 'Mật khẩu phải có ít nhất {min} ký tự.',
    'validation.password_match': 'Mật khẩu xác nhận không khớp.',
    'validation.name_min': 'Họ tên phải có ít nhất {min} ký tự.',
    'validation.terms': 'Vui lòng đồng ý điều khoản.',
    'validation.login_failed': 'Phản hồi đăng nhập không hợp lệ.',
    'landing.hero.title_1': 'Xây dựng Chatbot AI của bạn ',
    'landing.hero.title_2': 'trong vài phút',
    'landing.hero.subtitle': 'Huấn luyện AI bằng tài liệu của riêng bạn và cung cấp hỗ trợ khách hàng 24/7 mà không cần động tay.',
    'landing.hero.start': 'Bắt đầu miễn phí',
    'landing.hero.demo': 'Đặt lịch Demo',
    'landing.hero.social_proof': 'Hơn 500+ doanh nghiệp đã tự động hóa hỗ trợ',
    'landing.hero.mockup.preview': 'Xem trước trực tiếp',
    'landing.hero.mockup.bot_1': 'Xin chào! Tôi là trợ lý AI của bạn. Tôi có thể giúp gì cho bạn hôm nay?',
    'landing.hero.mockup.user': 'Làm thế nào để tích hợp cái này vào cửa hàng Shopify của tôi?',
    'landing.hero.mockup.bot_2': 'Tích hợp với Shopify rất dễ dàng! Chỉ cần cài đặt ứng dụng của chúng tôi từ Shopify App Store hoặc dán một dòng mã vào tệp theme.liquid của bạn.',
    'landing.hero.mockup.input': 'Nhập tin nhắn của bạn...',
    'landing.hero.badge': 'Mới: Tích hợp GPT-4o',
    'landing.features.title': 'Các tính năng mạnh mẽ cho doanh nghiệp của bạn',
    'landing.features.subtitle': 'Mọi thứ bạn cần để tự động hóa hỗ trợ khách hàng với trí tuệ nhân tạo đẳng cấp thế giới.',
    'landing.features.f1.title': 'AI được huấn luyện trên dữ liệu của bạn',
    'landing.features.f1.desc': 'Tải lên PDF, tài liệu hoặc trang web để huấn luyện bot của bạn ngay lập tức mà không cần lập trình.',
    'landing.features.f2.title': 'Tích hợp dễ dàng',
    'landing.features.f2.desc': 'Nhúng chatbot của bạn vào bất kỳ trang web nào chỉ với một dòng mã trong vài giây.',
    'landing.features.f3.title': 'Bảng điều khiển phân tích',
    'landing.features.f3.desc': 'Theo dõi hiệu suất, sự hài lòng của người dùng và thông tin chi tiết về lịch sử trò chuyện.',
    'landing.features.f4.title': 'Đa ngôn ngữ',
    'landing.features.f4.desc': 'Hỗ trợ khách hàng bằng hơn 100 ngôn ngữ một cách tự động và hoàn hảo.',
    'landing.pricing.title': 'Bảng giá đơn giản, minh bạch',
    'landing.pricing.subtitle': 'Chọn gói dịch vụ phù hợp với doanh nghiệp của bạn.',
    'landing.get_started': 'Bắt đầu ngay',
    'landing.nav.features': 'Tính năng',
    'landing.nav.how_it_works': 'Cách hoạt động',
    'landing.how.title': 'Cách hoạt động',
    'landing.how.subtitle': 'Thiết lập chatbot AI của bạn và đưa vào hoạt động chỉ với ba bước đơn giản.',
    'landing.how.step1.title': '1. Kết nối dữ liệu',
    'landing.how.step1.desc': 'Tải lên tài liệu hoặc liên kết trang web của bạn. Chúng tôi xử lý và lập chỉ mục nội dung của bạn một cách an toàn.',
    'landing.how.step2.title': '2. Tùy chỉnh Bot',
    'landing.how.step2.desc': 'Thiết lập giọng điệu, tính cách và giao diện của bot để phù hợp với nhận diện thương hiệu của bạn.',
    'landing.how.step3.title': '3. Nhúng & Tương tác',
    'landing.how.step3.desc': 'Sao chép một dòng mã để thêm widget vào trang web của bạn và bắt đầu hỗ trợ khách hàng.',
    'landing.nav.pricing': 'Bảng giá',
    'landing.nav.docs': 'Tài liệu',
    'landing.docs.title': 'Tài liệu dành cho nhà phát triển',
    'landing.docs.subtitle': 'Mọi thứ bạn cần để tích hợp WiseBot vào ứng dụng của mình.',
    'landing.docs.quickstart': 'Hướng dẫn bắt đầu nhanh',
    'landing.docs.quickstart.desc': 'Thiết lập và chạy trong vòng chưa đầy 5 phút.',
    'landing.docs.api': 'Tài liệu tham khảo API',
    'landing.docs.api.desc': 'Tài liệu chi tiết về các điểm cuối REST API của chúng tôi.',
    'landing.docs.sdks': 'Client SDKs',
    'landing.docs.sdks.desc': 'Thư viện cho React, Vue, Python và Node.js.',
    'landing.docs.webhooks': 'Webhooks',
    'landing.docs.webhooks.desc': 'Lắng nghe các sự kiện theo thời gian thực từ chatbot của bạn.',
    'landing.docs.view_all': 'Xem toàn bộ tài liệu',
    'landing.features.kb.title': 'Cơ sở tri thức',
    'landing.features.kb.desc': 'Tải lên PDF, DOCX hoặc URL để huấn luyện bot trên dữ liệu cụ thể của bạn.',
    'landing.features.widget.title': 'Widget tùy chỉnh',
    'landing.features.widget.desc': 'Widget trò chuyện có thể gắn thương hiệu hoàn toàn, phù hợp hoàn hảo với thiết kế trang web của bạn.',
    'landing.features.analytics.title': 'Phân tích nâng cao',
    'landing.features.analytics.desc': 'Theo dõi mọi cuộc trò chuyện và hiểu sâu hơn về hành vi người dùng.',
    'landing.features.api.title': 'API bảo mật',
    'landing.features.api.desc': 'Bảo mật cấp doanh nghiệp với các khóa API được mã hóa và kiểm soát truy cập.',
    'landing.features.cdn.title': 'CDN toàn cầu',
    'landing.features.cdn.desc': 'Phản hồi cực nhanh được phục vụ từ các vị trí biên trên toàn thế giới.',
    'landing.features.team.title': 'Cộng tác nhóm',
    'landing.features.team.desc': 'Mời nhóm của bạn và quản lý các vai trò với quyền hạn chi tiết.',
    'landing.pricing.popular': 'Phổ biến nhất',
    'landing.pricing.contact': 'Liên hệ bán hàng',
    'landing.pricing.free.name': 'Miễn phí',
    'landing.pricing.plus.name': 'Plus',
    'landing.pricing.pro.name': 'Pro',
    'landing.footer.tagline': 'Trao quyền cho các doanh nghiệp với các giải pháp AI thông minh thúc đẩy tăng trưởng và sự hài lòng của khách hàng.',
    'landing.footer.product': 'Sản phẩm',
    'landing.footer.company': 'Công ty',
    'landing.footer.legal': 'Pháp lý',
    'landing.footer.rights': '© 2024 WiseBot Inc. Bảo lưu mọi quyền.',
    'landing.footer.made_with': 'Được tạo với',
    'landing.footer.by_team': 'bởi đội ngũ WiseBot',
    'landing.footer.links.features': 'Tính năng',
    'landing.footer.links.pricing': 'Bảng giá',
    'landing.footer.links.docs': 'Tài liệu',
    'landing.footer.links.api': 'Tham chiếu API',
    'landing.footer.links.about': 'Về chúng tôi',
    'landing.footer.links.careers': 'Tuyển dụng',
    'landing.footer.links.blog': 'Blog',
    'landing.footer.links.contact': 'Liên hệ',
    'landing.footer.links.privacy': 'Chính sách bảo mật',
    'landing.footer.links.terms': 'Điều khoản dịch vụ',
    'landing.footer.links.cookie': 'Chính sách Cookie',
    'landing.footer.links.security': 'Bảo mật',
    'landing.pricing.free.f1': '1 Chatbot',
    'landing.pricing.free.f2': '1.000 Tin nhắn/tháng',
    'landing.pricing.free.f3': 'Hỗ trợ tiêu chuẩn',
    'landing.pricing.plus.f1': '5 Chatbots',
    'landing.pricing.plus.f2': '10.000 Tin nhắn/tháng',
    'landing.pricing.plus.f3': 'Phân tích nâng cao',
    'landing.pricing.plus.f4': 'Hỗ trợ ưu tiên',
    'landing.pricing.pro.f1': 'Không giới hạn Chatbots',
    'landing.pricing.pro.f2': 'Không giới hạn tin nhắn',
    'landing.pricing.pro.f3': 'Tùy chỉnh thương hiệu',
    'landing.pricing.pro.f4': 'Quyền truy cập API',
    'landing.pricing.pro.f5': 'Hỗ trợ riêng 24/7',
    'auth.reset.title': 'Đặt lại mật khẩu',
    'auth.reset.desc': 'Nhập email của bạn và chúng tôi sẽ gửi cho bạn một liên kết để đặt lại mật khẩu.',
    'auth.reset.submit': 'Gửi liên kết đặt lại',
    'auth.reset.back': 'Quay lại Đăng nhập',
    'auth.verify.title': 'Xác thực Email của bạn',
    'auth.verify.desc': 'Chúng tôi đã gửi một liên kết xác thực đến',
    'auth.verify.instruction': 'Vui lòng kiểm tra hộp thư đến của bạn và nhấp vào liên kết để kích hoạt tài khoản. Nếu bạn không thấy, hãy kiểm tra thư mục thư rác.',
    'auth.verify.resend': 'Gửi lại Email xác thực',
    'auth.verify.dashboard': 'Đi đến Bảng điều khiển',
    'widget.title': 'Tùy chỉnh Widget',
    'widget.subtitle': 'Cá nhân hóa giao diện chatbot trên trang web của bạn.',
    'widget.settings_tab': 'Cài đặt',
    'widget.preview_tab': 'Xem trước',
    'widget.identity': 'Danh tính Bot',
    'widget.display_name': 'Tên hiển thị',
    'widget.welcome_message': 'Lời chào mừng',
    'widget.bot_icon': 'Biểu tượng Bot',
    'widget.icon_color': 'Màu biểu tượng',
    'widget.branding': 'Thương hiệu & Phong cách',
    'widget.primary_color': 'Màu chủ đạo',
    'widget.position': 'Vị trí Widget',
    'widget.pos_left': 'Dưới cùng bên trái',
    'widget.pos_right': 'Dưới cùng bên phải',
    'widget.layout': 'Tùy chọn bố cục',
    'widget.show_citations': 'Hiển thị trích dẫn nguồn',
    'widget.enable_uploads': 'Cho phép tải tệp lên',
    'widget.publish': 'Xuất bản thay đổi',
    'widget.publishing': 'Đang xuất bản...',
    'widget.published': 'Đã xuất bản',
    'widget.publish_success': 'Cài đặt widget đã được xuất bản thành công!',
    'widget.embed_title': 'Nhúng vào trang web của bạn',
    'widget.embed_desc': 'Sao chép và dán mã này vào thẻ <head> của trang web của bạn.',
    'widget.copy_code': 'Sao chép mã',
    'widget.view_demo': 'Xem bản demo trực tiếp',
    'widget.view_demo_desc': 'Bạn muốn xem nó trông như thế nào trên một trang thực trước khi triển khai?',
    'demo.mode': 'Chế độ Demo',
    'demo.title': 'Xem trước trực tiếp: Trang web của bạn',
    'demo.nav.product': 'Sản phẩm',
    'demo.nav.solutions': 'Giải pháp',
    'demo.nav.pricing': 'Giá cả',
    'demo.hero.badge': 'Được tin dùng bởi hơn 500 công ty',
    'demo.hero.title_1': 'Tự động hóa',
    'demo.hero.title_2': 'Hỗ trợ khách hàng',
    'demo.hero.desc': 'Đây là bản demo trực tiếp về cách widget WiseBot đã tùy chỉnh của bạn sẽ hiển thị và hoạt động trên trang web thực tế của bạn. Trải nghiệm tích hợp liền mạch ngay lập tức.',
    'demo.hero.cta_primary': 'Bắt đầu dùng thử miễn phí',
    'demo.hero.cta_secondary': 'Đặt lịch hẹn Demo',
    'demo.feature.1.title': 'Câu trả lời tức thì',
    'demo.feature.1.desc': 'Giảm 70% số lượng yêu cầu hỗ trợ với các giải pháp tức thì do AI cung cấp, hiểu rõ ngữ cảnh.',
    'demo.feature.2.title': 'Dữ liệu an toàn',
    'demo.feature.2.desc': 'Dữ liệu của bạn được mã hóa và lưu trữ an toàn trong đám mây riêng của chúng tôi với tuân thủ SOC2.',
    'demo.feature.3.title': 'Đa ngôn ngữ',
    'demo.feature.3.desc': 'Hỗ trợ khách hàng của bạn bằng hơn 50 ngôn ngữ một cách tự động với bản dịch hoàn hảo.',
    'demo.testimonial.1.text': '"WiseBot đã hoàn toàn thay đổi cách chúng tôi tương tác với khách hàng. Việc thiết lập diễn ra tức thì và AI cực kỳ thông minh."',
    'demo.testimonial.1.author': 'Sarah Jenkins',
    'demo.testimonial.1.role': 'CEO tại TechFlow Global',
    'demo.testimonial.2.text': '"Việc tích hợp diễn ra vô cùng liền mạch. Đội ngũ hỗ trợ của chúng tôi hiện có thể tập trung vào các vấn đề phức tạp trong khi WiseBot xử lý các câu hỏi thường gặp một cách hoàn hảo."',
    'demo.testimonial.2.author': 'Mark Thompson',
    'demo.testimonial.2.role': 'Giám đốc Công nghệ tại InnovateX',
    'demo.testimonial.3.text': '"Khả năng học hỏi từ cơ sở tri thức của WiseBot thật ấn tượng. Nó cung cấp các câu trả lời chính xác trong vài giây, giúp cải thiện đáng kể sự hài lòng của khách hàng."',
    'demo.testimonial.3.author': 'Elena Rodriguez',
    'demo.testimonial.3.role': 'Quản lý Thành công Khách hàng tại CloudScale',
    'demo.cta.title': 'Sẵn sàng tăng năng suất của bạn?',
    'demo.cta.desc': 'Tham gia cùng hàng ngàn công ty đang sử dụng WiseBot để cung cấp sức mạnh cho đội ngũ thành công của khách hàng.',
    'demo.cta.button': 'Bắt đầu miễn phí',
    'demo.footer.privacy': 'Bảo mật',
    'demo.footer.terms': 'Điều khoản',
    'demo.footer.contact': 'Liên hệ',
    'demo.footer.copy': '© 2026 Công ty của bạn. Được cung cấp bởi WiseBot AI.',
    'widget.code_copied': 'Đã sao chép mã vào bộ nhớ tạm!',
    'widget.preview.online': 'Đang hoạt động',
    'widget.preview.ask': 'Đặt câu hỏi...',
    'api.title': 'Khóa API',
    'api.quickstart': 'Hướng dẫn nhanh về API',
    'api.subtitle': 'Quản lý quyền truy cập an toàn vào các mô hình và tài nguyên AI của bạn.',
    'api.generate': 'Tạo khóa mới',
    'api.table.name': 'Tên',
    'api.table.key': 'Khóa',
    'api.table.date': 'Ngày tạo',
    'api.table.used': 'Sử dụng lần cuối',
    'api.table.actions': 'Thao tác',
    'api.security.title': 'Thực hành tốt nhất về bảo mật API',
    'api.security.desc': 'Không bao giờ chia sẻ khóa API của bạn trong các kho lưu trữ công cộng hoặc mã phía máy khách. Sử dụng các biến môi trường để lưu trữ khóa của bạn một cách an toàn và thay đổi chúng thường xuyên để giảm thiểu rủi ro.',
    'api.security.guide': 'Xem hướng dẫn bảo mật',
    'api.docs.title': 'Tài liệu API',
    'api.docs.desc': 'Tìm hiểu cách tích hợp các mô hình AI của chúng tôi vào ứng dụng của bạn bằng tài liệu toàn diện, thư viện máy khách và SDK của chúng tôi.',
    'api.docs.read': 'Đọc tài liệu',
    'api.modal.title': 'Tạo khóa API mới',
    'api.modal.name': 'Tên khóa',
    'api.modal.placeholder': 'VD: Production Master',
    'api.modal.cancel': 'Hủy',
    'api.modal.success': 'Đã tạo khóa API thành công!',
    'api.modal.copy_msg': 'Hãy đảm bảo sao chép khóa API của bạn ngay bây giờ. Bạn sẽ không thể xem lại nó lần nữa.',
    'api.confirm.revoke.title': 'Thu hồi khóa API',
    'api.confirm.revoke.msg': 'Bạn có chắc chắn muốn thu hồi',
    'api.confirm.revoke.undone': 'Hành động này không thể hoàn tác và bất kỳ ứng dụng nào sử dụng khóa này sẽ ngừng hoạt động.',
    'api.copy.success': 'Đã sao chép khóa API vào bộ nhớ tạm!',
    'api.guide.title': 'Hướng dẫn bảo mật API',
    'api.guide.step1.title': 'Giữ bí mật các khóa của bạn',
    'api.guide.step1.desc': 'Khóa API cung cấp toàn quyền truy cập vào tài khoản của bạn. Không bao giờ đưa chúng vào hệ thống quản lý phiên bản (GitHub, GitLab) hoặc mã phía máy khách.',
    'api.guide.step2.title': 'Sử dụng biến môi trường',
    'api.guide.step2.desc': 'Lưu trữ các khóa trong tệp .env hoặc các dịch vụ lưu trữ bảo mật. Chỉ truy cập chúng ở phía máy chủ.',
    'api.guide.step3.title': 'Thay đổi khóa thường xuyên',
    'api.guide.step3.desc': 'Thay đổi khóa của bạn sau mỗi 90 ngày để giảm thiểu tác động nếu chẳng may bị rò rỉ.',
    'api.guide.step4.title': 'Hạn chế quyền truy cập',
    'api.guide.step4.desc': 'Tạo các khóa riêng biệt cho các môi trường khác nhau (Dev, Staging, Prod) để cô lập rủi ro.',
    'api.docs.modal.title': 'Tài liệu tham khảo API',
    'api.docs.endpoint.title': 'Endpoint cơ sở',
    'api.docs.auth.title': 'Xác thực',
    'api.docs.auth.desc': 'Tất cả các yêu cầu API phải bao gồm khóa API của bạn trong tiêu đề Authorization.',
    'api.docs.example.title': 'Ví dụ yêu cầu',
    'billing.title': 'Thanh toán & Gói dịch vụ',
    'billing.subtitle': 'Quản lý các gói giá, theo dõi doanh thu và giám sát đăng ký của người dùng.',
    'billing.create_plan': 'Tạo gói mới',
    'billing.payment_methods.title': 'Phương thức thanh toán',
    'billing.payment_methods.desc': 'Quản lý thẻ tín dụng và tùy chọn thanh toán của bạn.',
    'billing.payment_methods.add': 'Thêm phương thức',
    'billing.payment_methods.add_success': 'Đã thêm phương thức thanh toán thành công',
    'billing.payment_methods.save': 'Lưu phương thức thanh toán',
    'billing.payment_methods.delete_confirm': 'Xóa phương thức thanh toán?',
    'billing.payment_methods.delete_desc': 'Bạn có chắc chắn muốn xóa phương thức thanh toán này không?',
    'billing.payment_methods.delete_confirm_btn': 'Xóa',
    'billing.payment_methods.delete_success': 'Đã xóa phương thức thanh toán thành công.',
    'billing.payment_methods.primary': 'Mặc định',
    'billing.payment_methods.expires': 'Hết hạn',
    'billing.payment_methods.remove': 'Xóa',
    'billing.details.title': 'Thông tin hóa đơn',
    'billing.details.desc': 'Cập nhật địa chỉ thanh toán và thông tin thuế của bạn.',
    'billing.details.address': 'Địa chỉ thanh toán',
    'billing.details.city': 'Thành phố',
    'billing.details.country': 'Quốc gia',
    'billing.details.tax_id': 'Mã số thuế / VAT',
    'billing.plans.free': 'Miễn phí',
    'billing.plans.plus': 'Nâng cao',
    'billing.plans.pro': 'Chuyên nghiệp',
    'billing.plans.free.f1': 'Lên đến 1.000 tin nhắn',
    'billing.plans.free.f2': '1 Cơ sở tri thức',
    'billing.plans.free.f3': 'Hỗ trợ tiêu chuẩn',
    'billing.plans.plus.f1': 'Lên đến 10.000 tin nhắn',
    'billing.plans.plus.f2': '5 Cơ sở tri thức',
    'billing.plans.plus.f3': 'Hỗ trợ ưu tiên',
    'billing.plans.plus.f4': 'Truy cập API',
    'billing.plans.pro.f1': 'Không giới hạn tin nhắn',
    'billing.plans.pro.f2': 'Không giới hạn Cơ sở tri thức',
    'billing.plans.pro.f3': 'Hỗ trợ tận tâm',
    'billing.plans.pro.f4': 'Tích hợp tùy chỉnh',
    'billing.plans.pro.f5': 'Phân tích nâng cao',
    'billing.plans.select': 'Chọn gói',
    'billing.plans.current': 'Gói hiện tại',
    'billing.plans.popular': 'Phổ biến nhất',
    'billing.plans.features': 'Tính năng chính',
    'billing.plans.monthly': 'Hàng tháng',
    'billing.plans.yearly': 'Hàng năm',
    'billing.plans.save_20': 'Tiết kiệm 20%',
    'billing.plans.billed': 'Thanh toán',
    'billing.alerts.title': 'Cảnh báo sử dụng',
    'billing.alerts.desc': 'Nhận thông báo khi bạn đạt đến các ngưỡng sử dụng nhất định.',
    'billing.alerts.threshold': 'Ngưỡng thông báo',
    'billing.alerts.email': 'Gửi cảnh báo qua email',
    'billing.alerts.push': 'Gửi thông báo đẩy',
    'billing.mrr': 'Doanh thu định kỳ hàng tháng',
    'billing.active_subs': 'Đăng ký đang hoạt động',
    'billing.failed_payments': 'Thanh toán thất bại',
    'billing.recent_subs': 'Đăng ký gần đây',
    'billing.view_all': 'Xem tất cả',
    'billing.table.user': 'Người dùng',
    'billing.table.plan': 'Gói',
    'billing.table.amount': 'Số tiền',
    'billing.table.status': 'Trạng thái',
    'billing.table.next_billing': 'Kỳ thanh toán tiếp theo',
    'billing.table.action': 'Thao tác',
    'billing.manage': 'Quản lý',
    'billing.user.subtitle': 'Quản lý gói của bạn, phương thức thanh toán và xem hóa đơn.',
    'billing.payment_methods': 'Phương thức thanh toán',
    'billing.no_payment_methods': 'Chưa có phương thức thanh toán',
    'billing.no_payment_methods_desc': 'Vui lòng thêm phương thức thanh toán để tiếp tục nâng cấp.',
    'billing.upgrade': 'Nâng cấp gói',
    'billing.upgrade_desc': 'Chọn gói dịch vụ phù hợp với sự phát triển của bạn.',
    'billing.upgrade_success': 'Nâng cấp lên gói {plan} thành công!',
    'billing.downgrade_success': 'Đã chuyển về gói Miễn phí thành công.',
    'billing.current_plan': 'Gói hiện tại',
    'billing.current_plan.desc': 'Bạn hiện đang sử dụng',
    'billing.current_plan.next_billing': 'Ngày thanh toán tiếp theo',
    'billing.current_plan.need_more': 'Cần thêm tài nguyên?',
    'billing.payment_methods.manage': 'Quản lý các phương thức thanh toán đã lưu của bạn.',
    'billing.payment_methods.add_new': 'Thêm thẻ mới',
    'billing.payment_methods.cardholder_name': 'Tên chủ thẻ',
    'billing.payment_methods.card_number': 'Số thẻ',
    'billing.payment_methods.expiry': 'Ngày hết hạn',
    'billing.payment_methods.cvc': 'CVC',
    'billing.payment_methods.billing_address': 'Địa chỉ thanh toán',
    'billing.active': 'Đang hoạt động',
    'billing.free_forever': 'Miễn phí mãi mãi',
    'billing.pay_now': 'Thanh toán ngay',
    'billing.billed_monthly': 'Thanh toán hàng tháng',
    'billing.next_renewal': 'Gia hạn tiếp theo vào',
    'billing.cancel': 'Hủy đăng ký',
    'billing.usage.messages': 'Hạn mức tin nhắn',
    'billing.usage.storage': 'Lưu trữ cơ sở tri thức',
    'billing.usage.reset': 'Đặt lại sau',
    'billing.usage.capacity': 'tổng dung lượng đã sử dụng',
    'billing.secure_ssl': 'Mã hóa SSL bảo mật',
    'billing.cancel_anytime': 'Hủy bất cứ lúc nào',
    'billing.history': 'Lịch sử thanh toán',
    'billing.history_desc': 'Xem và tải xuống tất cả các hóa đơn trước đây của bạn.',
    'billing.table.invoice': 'Mã hóa đơn',
    'billing.table.date': 'Ngày',
    'billing.order_summary': 'Tóm tắt đơn hàng',
    'billing.total_due': 'Tổng thanh toán',
    'billing.payment_method': 'Phương thức thanh toán',
    'billing.secure_note': 'Thông tin thanh toán được mã hóa và bảo mật. Bạn có thể hủy bất cứ lúc nào.',
    'billing.no_plans': 'Không có gói nào',
    'billing.loading': 'Đang tải...',
    'billing.subscribing': 'Đang thiết lập gói...',
    'billing.no_data': 'Không có dữ liệu',
    'billing.plans.selected': 'Đã chọn',
    'common.back': 'Quay lại',
    'notifications.title': 'Thông báo',
    'notifications.view_all': 'Xem tất cả',
    'notifications.mark_read': 'Đánh dấu đã đọc',
    'notifications.empty': 'Không có thông báo mới',
    'notifications.new_message': 'Tin nhắn mới từ',
    'notifications.system_update': 'Cập nhật hệ thống',
    'notifications.billing_alert': 'Cảnh báo thanh toán',
    'playground.title': 'Cuộc hội thoại',
    'playground.clear': 'Xóa lịch sử chat',
    'playground.placeholder': 'Nhập tin nhắn của bạn...',
    'playground.sources': 'Trích dẫn nguồn',
    'playground.settings': 'Cài đặt mô hình',
    'playground.temp': 'Nhiệt độ (Temperature)',
    'playground.temp_desc': 'Kiểm soát tính ngẫu nhiên: Thấp hơn sẽ tập trung và xác định hơn.',
    'playground.topk': 'Top-K',
    'playground.topk_desc': 'Giới hạn từ vựng trong top K mã thông báo có khả năng nhất.',
    'playground.save': 'Lưu cấu hình',
    'playground.save_success': 'Đã lưu cấu hình thành công!',
    'playground.role.assistant': 'Trợ lý AI',
    'playground.role.user': 'Bạn',
    'kb.title': 'Cơ sở tri thức',
    'kb.subtitle': 'Quản lý các nguồn dữ liệu cung cấp phản hồi cho chatbot của bạn.',
    'kb.create': 'Tạo cơ sở tri thức',
    'kb.manage.title': 'Quản lý cơ sở tri thức',
    'kb.manage.subtitle': 'Chỉnh sửa, xóa hoặc đồng bộ hóa các nguồn dữ liệu hiện có của bạn.',
    'kb.no_sources': 'Không tìm thấy cơ sở tri thức nào.',
    'kb.sources.title': 'Nguồn dữ liệu được quản lý',
    'kb.upload.title': 'Tải lên tài liệu',
    'kb.upload.target': 'Cơ sở tri thức đích',
    'kb.upload.drop': 'Thả tệp vào đây hoặc nhấp để tải lên',
    'kb.upload.limit': 'Hỗ trợ PDF, DOCX, TXT (Tối đa 10MB)',
    'kb.recent.title': 'Tải lên gần đây',
    'kb.table.file': 'Tên tệp',
    'kb.table.type': 'Loại',
    'kb.table.status': 'Trạng thái',
    'kb.table.size': 'Kích thước',
    'kb.table.date': 'Ngày',
    'kb.table.showing': 'Đang hiển thị',
    'kb.table.of': 'trên',
    'kb.table.docs': 'tài liệu',
    'kb.modal.create': 'Tạo cơ sở tri thức',
    'kb.modal.edit': 'Chỉnh sửa cơ sở tri thức',
    'kb.modal.name': 'Tên',
    'kb.modal.name_placeholder': 'VD: FAQ hỗ trợ khách hàng',
    'kb.modal.desc': 'Mô tả',
    'kb.modal.desc_placeholder': 'Mô tả ngắn gọn nội dung của cơ sở tri thức này...',
    'kb.modal.type': 'Loại nguồn',
    'kb.modal.type.doc': 'Tải lên tài liệu',
    'kb.modal.type.doc_desc': 'Tải lên trực tiếp các tệp PDF, DOCX, TXT.',
    'kb.modal.type.web': 'Thu thập dữ liệu trang web',
    'kb.modal.type.web_desc': 'Trích xuất nội dung từ một trang web công cộng.',
    'kb.modal.type.notion': 'Tích hợp Notion',
    'kb.modal.type.notion_desc': 'Đồng bộ hóa các trang từ không gian làm việc Notion của bạn.',
    'kb.confirm.delete.title': 'Xóa cơ sở tri thức',
    'kb.confirm.delete.msg': 'Bạn có chắc chắn muốn xóa',
    'kb.confirm.delete.undone': 'Hành động này không thể hoàn tác.',
    'kb.confirm.edit.title': 'Xác nhận thay đổi',
    'kb.confirm.edit.msg': 'Bạn có chắc chắn muốn lưu các thay đổi cho',
    'kb.preview': 'Xem trước tài liệu',
    'kb.preview_desc': 'Đang xem bản xem trước của nội dung tài liệu.',
    'kb.preview_not_available': 'Xem trước không khả dụng cho loại tệp này.',
    'users.title': 'Quản lý người dùng',
    'users.subtitle': 'Quản lý tất cả người dùng hệ thống, vai trò toàn cầu và trạng thái tài khoản của họ.',
    'users.create': 'Tạo người dùng',
    'users.edit': 'Chỉnh sửa người dùng',
    'users.stats.total': 'Tổng người dùng',
    'users.stats.admins': 'Quản trị viên',
    'users.stats.active': 'Đang hoạt động',
    'users.stats.suspended': 'Đã tạm khóa',
    'users.table.user': 'Người dùng',
    'users.table.role': 'Vai trò toàn cầu',
    'users.table.workspaces': 'Không gian làm việc',
    'users.table.status': 'Trạng thái',
    'users.table.last_login': 'Lần đăng nhập cuối',
    'users.table.actions': 'Hành động',
    'users.no_users': 'Không tìm thấy người dùng nào.',
    'users.showing': 'Đang hiển thị',
    'users.users': 'người dùng',
    'users.details.title': 'Chi tiết người dùng',
    'users.confirm.delete.title': 'Xóa người dùng',
    'users.confirm.delete.msg': 'Bạn có chắc chắn muốn xóa người dùng',
    'users.confirm.delete.undone': 'Hành động này không thể hoàn tác.',
    'team.title': 'Quản lý nhóm',
    'team.subtitle': 'Mời và quản lý các thành viên trong nhóm và quyền hạn của họ.',
    'team.invite': 'Mời thành viên',
    'team.invite_new': 'Mời thành viên mới',
    'team.invite_sent': 'Đã gửi lời mời',
    'team.edit_member': 'Chỉnh sửa thành viên',
    'team.remove_member': 'Xóa thành viên',
    'team.no_members': 'Không tìm thấy thành viên nào.',
    'team.stats.total': 'Tổng thành viên',
    'team.stats.admins': 'Quản trị viên/Chủ sở hữu',
    'team.stats.pending': 'Lời mời đang chờ',
    'team.stats.seats': 'Số ghế đã dùng',
    'team.table.name': 'Tên',
    'team.table.email': 'Email',
    'team.table.role': 'Vai trò',
    'team.table.status': 'Trạng thái',
    'team.table.actions': 'Hành động',
    'team.showing': 'Đang hiển thị',
    'team.members': 'thành viên',
    'team.full_name': 'Họ và tên',
    'team.email_address': 'Địa chỉ email',
    'team.link_generated': 'Đã tạo liên kết mời',
    'team.link_sent_to': 'Một liên kết mời đã được tạo cho',
    'team.copy_manually': 'Sao chép liên kết thủ công',
    'team.copied': 'Đã sao chép vào khay nhớ tạm!',
    'team.copy': 'Sao chép',
    'team.invite_desc': 'Nhập email của người bạn muốn mời. Họ sẽ nhận được một liên kết để đăng ký và tham gia nhóm của bạn.',
    'team.generate_link': 'Tạo liên kết mời',
    'analytics.title': 'Phân tích',
    'analytics.subtitle': 'Theo dõi hiệu suất, mức độ tương tác của người dùng và xu hướng hội thoại.',
    'analytics.export': 'Xuất dữ liệu',
    'analytics.chart.volume': 'Lượng hội thoại',
    'analytics.chart.activity': 'Hoạt động thời gian thực',
    'analytics.admin.overview': 'Tổng quan Quản trị',
    'analytics.admin.total_users': 'Tổng người dùng',
    'analytics.admin.mrr': 'Doanh thu định kỳ (MRR)',
    'analytics.admin.system_health': 'Tình trạng hệ thống',
    'analytics.admin.api_requests': 'Yêu cầu API',
    'analytics.admin.user_growth': 'Tăng trưởng người dùng',
    'analytics.admin.plan_distribution': 'Phân bố Gói dịch vụ',
    'analytics.admin.system_load': 'Tải hệ thống',
    'analytics.admin.user_analytics': 'Phân tích người dùng',
    'analytics.admin.new_users': 'Người dùng mới',
    'analytics.admin.active_users': 'Người dùng hoạt động',
    'analytics.admin.stable': 'Ổn định',
    'analytics.admin.requests': 'Yêu cầu',
    'analytics.admin.errors': 'Lỗi',
    'analytics.admin.server_load': 'Tải máy chủ',
    'analytics.table.title': 'Các câu hỏi thường gặp nhất',
    'analytics.table.query': 'Câu hỏi',
    'analytics.table.count': 'Số lượng',
    'analytics.table.trend': 'Xu hướng',
    'analytics.view_full': 'Xem báo cáo đầy đủ',
    'analytics.period.7d': '7 ngày qua',
    'analytics.period.30d': '30 ngày qua',
    'analytics.period.90d': '90 ngày qua',
    'dashboard.chart.last_7d': '7 ngày qua',
    'dashboard.chart.last_30d': '30 ngày qua',
    'dashboard.chart.trend_up': '7 ngày qua (+15.3%)',
    'dashboard.category.billing': 'Thanh toán & Gói dịch vụ',
    'dashboard.category.security': 'Bảo mật tài khoản',
    'dashboard.category.api': 'Tài liệu API',
    'settings.profile': 'Cài đặt hồ sơ',
    'settings.profile.desc': 'Cập nhật thông tin cá nhân và hồ sơ công khai của bạn.',
    'settings.profile.title': 'Thông tin hồ sơ',
    'settings.security': 'Bảo mật & Quyền riêng tư',
    'settings.security.desc': 'Quản lý mật khẩu và cài đặt bảo mật tài khoản.',
    'settings.security.password': 'Đổi mật khẩu',
    'settings.security.password.desc': 'Thay đổi lần cuối 3 tháng trước',
    'settings.security.password.current': 'Mật khẩu hiện tại',
    'settings.security.password.new': 'Mật khẩu mới',
    'settings.security.password.confirm': 'Xác nhận mật khẩu mới',
    'settings.security.password.save': 'Cập nhật mật khẩu',
    'settings.security.password.cancel': 'Hủy',
    'settings.security.2fa': 'Xác thực hai yếu tố',
    'settings.security.2fa.desc': 'Đã bật • SMS & Ứng dụng xác thực',
    'settings.security.sessions': 'Phiên hoạt động',
    'settings.security.sessions.desc': 'Quản lý các thiết bị hiện đang đăng nhập',
    'settings.notifications': 'Tùy chọn thông báo',
    'settings.notifications.desc': 'Chọn những cập nhật bạn muốn nhận và cách thức nhận.',
    'settings.notifications.email': 'Thông báo qua Email',
    'settings.notifications.email.desc': 'Nhận tóm tắt hàng ngày và các cảnh báo quan trọng qua email.',
    'settings.notifications.push': 'Thông báo đẩy',
    'settings.notifications.push.desc': 'Nhận cập nhật thời gian thực trong trình duyệt của bạn.',
    'settings.notifications.marketing': 'Tiếp thị & Cập nhật',
    'settings.notifications.marketing.desc': 'Nhận tin tức về các tính năng mới và khuyến mãi.',
    'settings.notifications.save': 'Lưu tùy chọn',
    'settings.apps': 'Ứng dụng đã kết nối',
    'settings.apps.desc': 'Quản lý các tích hợp bên thứ ba và các dịch vụ đã kết nối.',
    'settings.apps.github': 'GitHub',
    'settings.apps.github.desc': 'Đã kết nối với tên @alexrivet',
    'settings.apps.slack': 'Slack',
    'settings.apps.slack.desc': 'Chưa kết nối',
    'settings.apps.trello': 'Trello',
    'settings.apps.trello.desc': 'Chưa kết nối',
    'settings.apps.disconnect': 'Ngắt kết nối',
    'settings.apps.connect': 'Kết nối',
    'settings.workspace': 'Cài đặt không gian làm việc',
    'settings.workspace.desc': 'Quản lý cấu hình không gian làm việc toàn cầu và thanh toán.',
    'settings.workspace.name': 'Tên không gian làm việc',
    'settings.workspace.members': 'Quản lý thành viên',
    'settings.workspace.members.desc': 'Mời người dùng và quản lý vai trò.',
    'settings.workspace.billing': 'Thanh toán & Gói dịch vụ',
    'settings.workspace.billing.desc': 'Xem hóa đơn và nâng cấp gói.',
    'settings.workspace.danger': 'Khu vực nguy hiểm',
    'settings.workspace.danger.desc': 'Một khi bạn xóa không gian làm việc, không thể quay lại. Hãy chắc chắn.',
    'settings.workspace.delete': 'Xóa không gian làm việc',
    'header.internal_workspace': 'Không gian làm việc nội bộ',
    'header.ai_platform': 'WiseBot',
    'settings.title': 'Cài đặt',
    'settings.description': 'Quản lý tùy chọn tài khoản và cấu hình không gian làm việc của bạn.',
    'settings.language': 'Cài đặt ngôn ngữ',
    'settings.language.desc': 'Chọn ngôn ngữ ưu tiên của bạn cho giao diện.',
    'settings.language.select': 'Chọn ngôn ngữ',
    'common.create': 'Tạo mới',
    'common.save': 'Lưu thay đổi',
    'common.save_short': 'Lưu',
    'common.cancel': 'Hủy',
    'common.change': 'Thay đổi',
    'common.processing': 'Đang xử lý...',
    'common.english': 'Tiếng Anh',
    'common.vietnamese': 'Tiếng Việt',
    'common.search': 'Tìm kiếm...',
    'common.edit': 'Chỉnh sửa',
    'common.delete': 'Xóa',
    'common.done': 'Hoàn tất',
    'common.select': 'Chọn tệp',
    'common.prev': 'Trước',
    'common.next': 'Sau',
    'common.confirm': 'Xác nhận',
    'common.retry': 'Thử lại',
    'common.view_details': 'Xem chi tiết',
    'common.cannot_be_undone': 'Hành động này không thể hoàn tác.',
    'billing.support.phone': 'Số điện thoại',
    'toast.login_success': 'Đăng nhập thành công!',
    'toast.signup_success': 'Tài khoản đã được tạo thành công!',
    'toast.profile_updated': 'Đã cập nhật hồ sơ thành công!',
    'toast.logout_success': 'Đã đăng xuất thành công.',
    'toast.kb_created': 'Đã tạo cơ sở tri thức thành công!',
    'toast.kb_updated': 'Đã cập nhật cơ sở tri thức thành công!',
    'toast.kb_deleted': 'Đã xóa cơ sở tri thức thành công.',
    'toast.file_uploaded': 'Đã tải tệp lên thành công!',
    'toast.api_generated': 'Đã tạo khóa API thành công!',
    'toast.api_revoked': 'Đã thu hồi khóa API thành công.',
    'toast.user_created': 'Đã tạo người dùng thành công!',
    'toast.user_updated': 'Đã cập nhật người dùng thành công!',
    'toast.user_deleted': 'Đã xóa người dùng thành công.',
    'toast.error': 'Đã có lỗi xảy ra. Vui lòng thử lại.',
    'status.synced': 'Đã đồng bộ',
    'status.live_sync': 'Đồng bộ trực tiếp',
    'status.idle': 'Chờ',
    'status.completed': 'Hoàn thành',
    'status.processing': 'Đang xử lý',
    'status.failed': 'Thất bại',
    'settings.profile.timezone': 'Múi giờ',
    'settings.profile.plan_pro': 'Gói Pro',
    'role.admin': 'QUẢN TRỊ',
    'role.owner': 'CHỦ SỞ HỮU',
    'role.user': 'NGƯỜI DÙNG',
    'profile.edit': 'Chỉnh sửa hồ sơ',
    'profile.settings': 'Cài đặt tài khoản',
    'profile.sign_out': 'Đăng xuất',
    'profile.joined': 'Đã tham gia',
    'profile.personal_info': 'Thông tin cá nhân',
    'profile.personal_info_desc': 'Cập nhật thông tin cá nhân và cách người khác nhìn thấy bạn.',
    'profile.security': 'Bảo mật tài khoản',
    'profile.security.password': 'Đổi mật khẩu',
    'profile.security.password_desc': 'Cập nhật mật khẩu để giữ tài khoản của bạn an toàn.',
    'profile.security.current_password': 'Mật khẩu hiện tại',
    'profile.security.new_password': 'Mật khẩu mới',
    'profile.security.confirm_password': 'Xác nhận mật khẩu mới',
    'profile.security.2fa': 'Xác thực 2 yếu tố (2FA)',
    'profile.security.2fa_desc': 'Thêm một lớp bảo mật bổ sung cho tài khoản của bạn.',
    'profile.security.2fa_enable': 'Bật 2FA',
    'profile.security.2fa_disable': 'Tắt 2FA',
    'profile.security.2fa_status_on': 'Đã bật',
    'profile.security.2fa_status_off': 'Đã tắt',
    'profile.security.update_password': 'Cập nhật mật khẩu',
    'profile.security.authenticator_app': 'Ứng dụng xác thực',
    'profile.security.authenticator_desc': 'Sử dụng ứng dụng như Google Authenticator hoặc Authy.',
    'profile.security.danger_zone': 'Khu vực nguy hiểm',
    'profile.security.delete_account': 'Xóa tài khoản',
    'profile.security.delete_account_desc': 'Xóa vĩnh viễn tài khoản và tất cả nội dung của bạn.',
    'profile.stats.workspaces': 'Không gian làm việc',
    'profile.stats.chatbots': 'Chatbot',
    'profile.stats.messages': 'Tin nhắn',
    'profile.stats.team': 'Thành viên nhóm',
    'profile.bio': 'Tiểu sử',
    'profile.location': 'Vị trí',
    'profile.social_links': 'Liên kết mạng xã hội',
    'profile.website': 'Trang web',
    'profile.twitter': 'Twitter',
    'profile.github': 'GitHub',
    'profile.linkedin': 'LinkedIn',
    'profile.timezone': 'Múi giờ',
    'profile.language_region': 'Ngôn ngữ & Khu vực',
    'settings.system': 'Cài đặt hệ thống',
    'settings.system.desc': 'Quản lý các tùy chọn hệ thống như ngôn ngữ và giao diện.',
    'settings.appearance': 'Giao diện',
    'settings.appearance.desc': 'Tùy chỉnh cách giao diện hiển thị trên thiết bị của bạn.',
    'settings.theme.light': 'Chế độ sáng',
    'settings.theme.dark': 'Chế độ tối',
    'settings.theme.system': 'Theo hệ thống',
    'profile.plan_pro_badge': 'Thành viên Pro',
    'profile.delete_account': 'Xóa tài khoản',
    'profile.delete_account_desc': 'Xóa vĩnh viễn tài khoản của bạn và tất cả dữ liệu liên quan.',
    'profile.view_public': 'Xem hồ sơ công khai',
    'profile.overview': 'Tổng quan',
    'profile.repositories': 'Kho lưu trữ',
    'profile.projects': 'Dự án',
    'profile.packages': 'Gói',
    'profile.stars': 'Dấu sao',
    'profile.followers': 'người theo dõi',
    'profile.following': 'đang theo dõi',
    'profile.pinned': 'Đã ghim',
    'profile.pinned_agents': 'Agent đã ghim',
    'profile.activity': 'Hoạt động',
    'profile.conversations_handled': 'cuộc hội thoại đã xử lý trong năm qua',
    'profile.contributions': 'đóng góp trong năm qua',
    'billing.payment_methods.set_primary': 'Đặt làm mặc định',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('vi');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
